In [7]:
# To calculate determinant
import numpy as np
from numpy import linalg as la

In [8]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
la.det(a)

6.66133814775094e-16

In [10]:
# To calculate co factor, adjoint, Inverse

In [11]:
from numpy import linalg as la
import numpy as np

In [12]:
a=np.array([[1,3],[2,4]])
a

array([[1, 3],
       [2, 4]])

In [13]:
la.inv(a)

array([[-2. ,  1.5],
       [ 1. , -0.5]])

In [14]:
import numpy as py


In [15]:
x=np.array([[150,5,1],[100,5,1],[120,10,1]])
x

array([[150,   5,   1],
       [100,   5,   1],
       [120,  10,   1]])

In [16]:
y=np.array([100,60,90])
y

array([100,  60,  90])

In [17]:
np.linalg.inv(x)

array([[ 2.00000000e-02, -2.00000000e-02, -7.40148683e-19],
       [-8.00000000e-02, -1.20000000e-01,  2.00000000e-01],
       [-1.60000000e+00,  3.60000000e+00, -1.00000000e+00]])

In [18]:
np.linalg.inv(x)@y

array([  0.8,   2.8, -34. ])

In [21]:
0.8*100+2.8*5-34

60.0

In [20]:
.8*180+2.8*19-34

163.2

In [22]:
#Eigen vector and Eigen